# Generated by Django 5.0.1 on 2024-01-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_username_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcontact',
            name='spam_points',
            field=models.IntegerField(default=0),
        ),
    ]
